/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunitiesSplatRouteImport } from './routes/communities/$'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteImport } from './routes/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesSplatRoute = CommunitiesSplatRouteImport.update({
  id: '/communities/$',
  path: '/communities/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute =
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteImport.update({
    id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber',
    path: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/$path': typeof AuthPathRoute
  '/communities/$': typeof CommunitiesSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/$path': typeof AuthPathRoute
  '/communities/$': typeof CommunitiesSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/$path': typeof AuthPathRoute
  '/communities/$': typeof CommunitiesSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber': typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/$path'
    | '/communities/$'
    | '/api/auth/$'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/$path'
    | '/communities/$'
    | '/api/auth/$'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
  id:
    | '__root__'
    | '/'
    | '/auth/$path'
    | '/communities/$'
    | '/api/auth/$'
    | '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthPathRoute: typeof AuthPathRoute
  CommunitiesSplatRoute: typeof CommunitiesSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$': {
      id: '/communities/$'
      path: '/communities/$'
      fullPath: '/communities/$'
      preLoaderRoute: typeof CommunitiesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber': {
      id: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
      path: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
      fullPath: '/courses/$year/$periodType/$periodNumber/$courseCode/$groupNumber'
      preLoaderRoute: typeof CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthPathRoute: AuthPathRoute,
  CommunitiesSplatRoute: CommunitiesSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute:
    CoursesYearPeriodTypePeriodNumberCourseCodeGroupNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
